import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

// Supabase Dashboard > Project Settings > API 에서 값을 넣으세요.
const SUPABASE_URL = 'https://szbgewudwfaiwzbajzzg.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_eHs5l0kOSduUNeszDrjPEA_rRvUT6VG';
const configured = !SUPABASE_URL.includes('YOUR_') && !SUPABASE_ANON_KEY.includes('YOUR_');
const supabase = configured ? createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const $ = (s) => document.querySelector(s);
const main = $('#main-content');
let state = { user: null, profile: null, records: [], settings: null, athletes: [], teams: [] };
const kinds = { cycle: ['🚴','사이클','km'], swim: ['🏊','수영','m'], run: ['🏃','러닝','km'], strength: ['🏋️','보강운동','min'] };

function toast(message) { const t=$('#toast'); t.textContent=message; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),2600); }
function nav(active) { $('#bottom-nav').innerHTML = [['record','✚','기록입력'],['me','◎','내 점수'],['team','♜','팀 점수'], ...(state.profile?.role==='admin'?[['admin','⚙','관리']]:[])].map(([id,icon,label])=>`<a href="#${id}" class="${active===id?'active':''}"><span>${icon}</span>${label}</a>`).join(''); }
function score(r) { const threshold=Number(state.settings?.[`${r.exercise_type}_target`]||0); return Number(r.amount)>=threshold ? 1 : 0; }
function total(records) { return records.reduce((a,r)=>a+score(r),0); }
function topbar(){ $('#user-area').innerHTML=state.user?`<div class="user-tools"><span class="email">${state.profile?.display_name||state.user.email}</span><button class="btn outline small" id="logout">로그아웃</button></div>`:''; $('#logout')?.addEventListener('click',async()=>{await supabase.auth.signOut();location.hash='';}); }

function loginPage(){ main.innerHTML=`<section class="login"><a class="brand" href="#"><span>TC</span><strong>철안철인클럽</strong></a><div class="card"><h2>운동기록 로그인</h2><p class="hint">가입한 이메일과 비밀번호로 로그인하세요.</p><form id="login-form"><div class="field"><label>이메일</label><input name="email" type="email" required placeholder="name@example.com"></div><div class="field"><label>비밀번호</label><input name="password" type="password" required minlength="6"></div><button class="btn full">로그인</button></form><p class="hint">처음이신가요? <a href="#signup">회원가입</a></p></div></section>`; $('#login-form').onsubmit=async(e)=>{e.preventDefault();const d=new FormData(e.target);const {error}=await supabase.auth.signInWithPassword({email:d.get('email'),password:d.get('password')});if(error)toast('로그인에 실패했습니다. 이메일과 비밀번호를 확인해 주세요.');}; }
function signupPage(){ main.innerHTML=`<section class="login"><a class="brand" href="#"><span>TC</span><strong>철안철인클럽</strong></a><div class="card"><h2>철안철인클럽 회원가입</h2><p class="hint">가입 후 바로 운동 기록을 시작할 수 있습니다.</p><form id="signup-form"><div class="field"><label>이름</label><input name="display_name" required maxlength="30" placeholder="실명 또는 클럽에서 쓰는 이름"></div><div class="field"><label>이메일</label><input name="email" type="email" required placeholder="name@example.com"></div><div class="field"><label>비밀번호</label><input name="password" type="password" required minlength="8" placeholder="8자 이상"></div><button class="btn orange full">회원가입</button></form><p class="hint">이미 계정이 있나요? <a href="#record">로그인</a></p></div></section>`; $('#signup-form').onsubmit=async(e)=>{e.preventDefault();const d=new FormData(e.target);const {data,error}=await supabase.auth.signUp({email:d.get('email'),password:d.get('password'),options:{data:{display_name:d.get('display_name')}}});if(error)return toast(error.message);if(data.session)toast('가입되었습니다. 운동 기록을 시작해 보세요!');else toast('가입 확인 이메일을 보냈습니다. 이메일 확인 후 로그인해 주세요.');};}
function setupWarning(){return !configured?'<div class="notice">아직 Supabase 연결 정보가 설정되지 않았습니다. README의 1~3단계를 완료한 뒤 app.js의 두 값을 입력하세요.</div>':''}
function recordPage(){nav('record');main.innerHTML=`<section class="page"><div class="hero"><h1>오늘도 한 걸음 더! 💪</h1><p>${state.profile.display_name}님의 운동을 기록해 보세요.</p></div>${setupWarning()}<div class="card"><h2>운동 기록 입력</h2><form id="record-form"><div class="grid"><div class="field"><label>운동 종류</label><select name="exercise_type">${Object.entries(kinds).map(([v,k])=>`<option value="${v}">${k[0]} ${k[1]}</option>`).join('')}</select></div><div class="field"><label>운동 날짜</label><input name="performed_on" type="date" value="${new Date().toISOString().slice(0,10)}" required></div></div><div class="field"><label>운동량</label><div class="input-addon"><input name="amount" type="number" min="0" step="0.1" required placeholder="예: 10"><span id="unit">km</span></div><p class="hint" id="target-hint"></p></div><div class="field"><label>메모 <em>(선택)</em></label><textarea name="memo" placeholder="코스, 컨디션 등을 남겨보세요."></textarea></div><div class="field"><label>운동 캡처 첨부 <em>(선택, 최대 10MB)</em></label><input name="attachment" type="file" accept="image/*"><p class="hint">Strava, Garmin 등 캡처 이미지를 올릴 수 있습니다.</p></div><button class="btn orange full">운동 기록 저장</button></form></div><div class="section-title"><h2>최근 운동</h2><a href="#me" class="hint">전체 보기</a></div><div class="card" id="recent-records"></div></section>`; const form=$('#record-form'), sel=form.exercise_type; const refresh=()=>{const k=kinds[sel.value], target=state.settings?.[`${sel.value}_target`]||0;$('#unit').textContent=k[2];$('#target-hint').textContent=`점수 기준: ${target}${k[2]} 이상 = 1점`;};sel.onchange=refresh;refresh(); renderRecords('#recent-records',state.records.slice(0,5)); form.onsubmit=saveRecord;}
function renderRecords(selector,records){const root=$(selector);if(!records.length){root.innerHTML='<div class="empty">아직 등록된 운동이 없습니다.</div>';return;}root.innerHTML=records.map(r=>`<div class="record"><div class="record-icon">${kinds[r.exercise_type]?.[0]}</div><div class="record-main"><b>${kinds[r.exercise_type]?.[1]} ${r.amount}${kinds[r.exercise_type]?.[2]}</b><small>${r.performed_on}${r.memo?' · '+escapeHtml(r.memo):''}</small></div><div class="record-score">+${score(r)}점<small>${score(r)?'목표 달성':'목표 미달'}</small></div></div>`).join('')}
async function saveRecord(e){e.preventDefault();if(!configured)return toast('Supabase 연결 정보를 먼저 입력해 주세요.');const f=new FormData(e.target),file=f.get('attachment');let attachment_url=null;if(file?.size){if(file.size>10*1024*1024)return toast('첨부파일은 10MB 이하여야 합니다.');const path=`${state.user.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await supabase.storage.from('workout-images').upload(path,file);if(error)return toast('파일 업로드 실패: '+error.message);attachment_url=supabase.storage.from('workout-images').getPublicUrl(path).data.publicUrl;}const {error}=await supabase.from('workout_records').insert({user_id:state.user.id,exercise_type:f.get('exercise_type'),amount:Number(f.get('amount')),performed_on:f.get('performed_on'),memo:f.get('memo'),attachment_url});if(error)return toast('저장 실패: '+error.message);toast('운동 기록을 저장했습니다!');await loadData();recordPage();}
function mePage(){nav('me'); const mine=state.records; const by=Object.keys(kinds).map(t=>`${kinds[t][0]} ${total(mine.filter(r=>r.exercise_type===t))}점`).join(' · ');main.innerHTML=`<section class="page"><div class="hero"><p>${state.profile.display_name}님의 누적 점수</p><h1>${total(mine)}점</h1><p>${by}</p></div><div class="section-title"><h2>내 운동 기록</h2></div><div class="card" id="my-records"></div></section>`;renderRecords('#my-records',mine)}
async function teamPage(){nav('team'); const {data:all,error}=await supabase.from('workout_records').select('*,profiles!inner(display_name,team_id,teams(name))').order('performed_on',{ascending:false});if(error)return toast(error.message);const scores={};(all||[]).forEach(r=>{const n=r.profiles?.teams?.name||'미배정';scores[n]=(scores[n]||0)+score(r)});main.innerHTML=`<section class="page"><div class="hero"><h1>팀 점수판 🏆</h1><p>목표 기준을 달성한 운동 1건당 1점입니다.</p></div><div class="card"><div class="table-wrap"><table><thead><tr><th>순위</th><th>팀</th><th>누적 점수</th></tr></thead><tbody>${Object.entries(scores).sort((a,b)=>b[1]-a[1]).map(([n,s],i)=>`<tr><td>${i+1}</td><td>${n}</td><td><b>${s}점</b></td></tr>`).join('')||'<tr><td colspan="3" class="empty">집계할 기록이 없습니다.</td></tr>'}</tbody></table></div></div></section>`;}
function adminPage(){nav('admin');main.innerHTML=`<section class="page"><div class="hero"><h1>관리자 화면 ⚙</h1><p>점수 기준과 팀을 관리합니다.</p></div><div class="admin-grid"><div class="card"><h2>점수 기준 설정</h2><form id="settings-form">${Object.entries(kinds).map(([key,k])=>`<div class="field"><label>${k[0]} ${k[1]} 기준 (${k[2]})</label><input name="${key}_target" type="number" min="0" step="0.1" value="${state.settings?.[key+'_target']??0}" required></div>`).join('')}<button class="btn full">기준 저장</button></form></div><div class="card"><h2>회원 팀 배정</h2><form id="team-form"><div class="field"><label>회원</label><select name="user_id">${state.athletes.map(p=>`<option value="${p.id}">${p.display_name} (${p.teams?.name||'미배정'})</option>`).join('')}</select></div><div class="field"><label>팀</label><select name="team_id"><option value="">미배정</option>${state.teams.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select></div><button class="btn full">팀 배정 저장</button></form><hr><form id="new-team-form"><div class="field"><label>새 팀 이름</label><input name="name" required placeholder="예: A팀"></div><button class="btn outline full">팀 만들기</button></form></div></div><div class="card"><h2>개인별 점수 리포트</h2><div class="table-wrap"><table><thead><tr><th>이름</th><th>팀</th><th>누적 점수</th></tr></thead><tbody>${state.athletes.map(p=>`<tr><td>${p.display_name}</td><td>${p.teams?.name||'-'}</td><td>${total(state.records.filter(r=>r.user_id===p.id))}점</td></tr>`).join('')}</tbody></table></div></div></section>`; $('#settings-form').onsubmit=saveSettings;$('#team-form').onsubmit=assignTeam;$('#new-team-form').onsubmit=createTeam;}
async function saveSettings(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));Object.keys(d).forEach(k=>d[k]=Number(d[k]));const {error}=await supabase.from('club_settings').upsert({id:1,...d});if(error)toast(error.message);else{toast('점수 기준을 저장했습니다.');await loadData();}}
async function assignTeam(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const {error}=await supabase.from('profiles').update({team_id:d.team_id||null}).eq('id',d.user_id);if(error)toast(error.message);else{toast('팀을 배정했습니다.');await loadData();adminPage();}}
async function createTeam(e){e.preventDefault();const {error}=await supabase.from('teams').insert({name:new FormData(e.target).get('name')});if(error)toast(error.message);else{toast('팀을 만들었습니다.');await loadData();adminPage();}}
function escapeHtml(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function loadData(){const [p,r,s,a,t]=await Promise.all([supabase.from('profiles').select('*,teams(name)').eq('id',state.user.id).single(),supabase.from('workout_records').select('*').eq('user_id',state.user.id).order('performed_on',{ascending:false}),supabase.from('club_settings').select('*').eq('id',1).single(),supabase.from('profiles').select('*,teams(name)').order('display_name'),supabase.from('teams').select('*').order('name')]);state.profile=p.data;state.records=r.data||[];state.settings=s.data;state.athletes=a.data||[];state.teams=t.data||[];}
async function route(){if(!configured){state.user={email:'미리보기'};state.profile={display_name:'클럽 회원',role:'admin'};state.settings={cycle_target:20,swim_target:1000,run_target:5,strength_target:30};state.records=[];state.athletes=[];state.teams=[];topbar();recordPage();return;}const {data:{session}}=await supabase.auth.getSession();state.user=session?.user||null;if(!state.user){$('#user-area').innerHTML='';$('#bottom-nav').innerHTML='';return location.hash==='#signup'?signupPage():loginPage();}await loadData();topbar();const page=location.hash.slice(1)||'record';({record:recordPage,me:mePage,team:teamPage,admin:state.profile?.role==='admin'?adminPage:recordPage}[page]||recordPage)();}
window.addEventListener('hashchange',route);if(configured)supabase.auth.onAuthStateChange(()=>route());route();
